version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: nodejs-prisma-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: prisma_encryption_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma_user -d prisma_encryption_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prisma-network

volumes:
  postgres_data:
    driver: local

networks:
  prisma-network:
    driver: bridge
