version: '3.8'

services:
  azuresql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: nodejs-prisma-azure-sql-edge
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: prisma_password # user is 'sa'
      MSSQL_PID: Premium
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P prisma_password -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prisma-network

volumes:
  sqlserver:
    driver: local

networks:
  prisma-network:
    driver: bridge
